version: 2
updates:
  - package-ecosystem: bundler
    directory: /single
    schedule:
      interval: weekly
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: bundler
    directory: /working
    schedule:
      interval: weekly
  - package-ecosystem: bundler
    directory: /grouped
    schedule:
      interval: weekly
    groups:
      test:
        applies-to: version-updates
        patterns:
          - business
          - statesman
